import { InferSchemaType, Schema, model } from "mongoose"

const noteSchema = new Schema({
    userId: { type: Schema.Types.ObjectId, required: true },
    firstname: { type: String, required: true },
    lastname: { type: String },
    phoneno: { type: String },
    importantdetails: { type: String },
    c1a: { type: String },
    c1b: { type: String },
    c1c: { type: String },
    c1d: { type: String },
    c1e: { type: String },
    c1f: { type: String },
    c1g: { type: String },
    c1h: { type: String },
    c2a: { type: String },
    c2b: { type: String },
    c2c: { type: String },
    c2d: { type: String },
    c2e: { type: String },
    c2f: { type: String },
    c2g: { type: String },
    c2h: { type: String },
    c3a: { type: String },
    c3b: { type: String },
    c3c: { type: String },
    c3d: { type: String },
    c3e: { type: String },
    c3f: { type: String },
    c3g: { type: String },
    c3h: { type: String },
    c4a: { type: String },
    c4b: { type: String },
    c4c: { type: String },
    c4d: { type: String },
    c4e: { type: String },
    c4f: { type: String },
    c4g: { type: String },
    c4h: { type: String },
}, { timestamps: true })

type Note = InferSchemaType<typeof noteSchema>

export default model<Note>("Note", noteSchema)