import { InferSchemaType, Schema, model } from "mongoose"

const noteSchema = new Schema({
    userId: { type: Schema.Types.ObjectId, required: true },
    firstname: { type: String, required: true },
    lastname: { type: String },
    phoneno: { type: String },
    importantdetails: { type: String },
    age: { type: String },
    cnp: { type: String },
    reason: { type: String },
    a1: { type: String },
    a2: { type: String },
    a3: { type: String },
    a4: { type: String },
    a5: { type: String },
    a6: { type: String },
    a7: { type: String },
    a8: { type: String },
    a9: { type: String },
    a10: { type: String },
    a11: { type: String },
    a12: { type: String },
    a13: { type: String },
    b1: { type: String },
    b2: { type: String },
    b3: { type: String },
    b4: { type: String },
    b5: { type: String },
    b6: { type: String },
    b7: { type: String },
    b8: { type: String },
    b9: { type: String },
    b10: { type: String },
    b11: { type: String },
    b12: { type: String },
    b13: { type: String },
    c1: { type: String },
    c2: { type: String },
    c3: { type: String },
    c4: { type: String },
    c5: { type: String },
    c6: { type: String },
    c7: { type: String },
    c8: { type: String },
    c9: { type: String },
    c10: { type: String },
    c11: { type: String },
    c12: { type: String },
    c13: { type: String },
    d1: { type: String },
    d2: { type: String },
    d3: { type: String },
    d4: { type: String },
    d5: { type: String },
    d6: { type: String },
    d7: { type: String },
    d9: { type: String },
    d8: { type: String },
    d11: { type: String },
    d10: { type: String },
    d13: { type: String },
    d12: { type: String },
    currentColor: { type: String },
    currentColorIndex: { type: String },
    control: { type: String },
    name: { type: String },
    select: { type: String },
}, { timestamps: true })

type Note = InferSchemaType<typeof noteSchema>

export default model<Note>("Note", noteSchema)